# Site configuration
domain: "https://marcoaasilva.github.io"
#domain: "http://localhost:3000"
baseurl: "jekyll-crazymentat" # the subpath of your site, e.g. /blog/
#baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://marcoaasilva.github.io/jekyll-crazymentat" # the base hostname & protocol for your sitez
#url: "http://localhost:3000"
permalink: /:title/
avatar: https://marcoaasilva.github.io/jekyll-crazymentat/img/jekyll-maas.png
favicon: /img/favicon.ico
basecss: 
# Theme specific configuration
title: crazymentat
description: >
  Hi there, my name is Marco Silva.
  I usually use "dreamcaster" or "MarcoAASilva" as my ID everywhere.
  I was born and raised in Brazil.  I live in Porto Alegre.
  I'm really fond of programming, scifi and philosophy.
# Contact and social media links

exclude: ['node_modules', 'gulpfile.js', 'package.json']

kramdown:
  input: GFM

# If U enable the comment, edit disqus or duoshuo account of "/_layouts/post.html"
# before deploy your webpage
enable_comment: false

gems: ['jekyll-paginate']
# Pagination
paginate: 5
paginate_path: /archive/page:num
