# Site configuration
domain: "http://songroger.win"
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://127.0.0.1:3000" # the base hostname & protocol for your sitez
permalink: /:title/
avatar: /img/jekyll-maas.png
favicon: /img/favicon.ico
basecss: 
# Theme specific configuration
title: crazymentat
description: >
  Hi there, my name is Marco Silva.
  I usually use "dreamcaster" or "MarcoAASilva" as my ID everywhere.
  I was born and raised in Brazil.  I live in Porto Alegre.
  I'm really fond of programming, scifi and philosophy.
# Contact and social media links

exclude: ['node_modules', 'gulpfile.js', 'package.json']

kramdown:
  input: GFM

# If U enable the comment, edit disqus or duoshuo account of "/_layouts/post.html"
# before deploy your webpage
enable_comment: false

gems: ['jekyll-paginate']
# Pagination
paginate: 5
paginate_path: /archive/page:num
